### ISSUE TITLE
Allow `fgh ls` to use case-insensitive match

### ISSUE THREAD

**Issue by cgranade** [Matt-Gleich/fgh#11]
## Description

If reasonable, it would be pretty nice for `fgh ls` to allow reporting paths for repos without requiring a case-sensitive match. Especially on case-insensitive filesystems such as are common on Windows, the casing for the path on disk may not match the casing found by `OwnerAndNameFromRemote`, such that `fgh ls` can fail even when the repo name provided matches the casing on disk.

**Comment by Matt-Gleich** [comment]
This is totally something I can do! Expect a PR soon.

**Comment by Matt-Gleich** [comment]
This is now available in v2.0.1. Thanks again for the suggestion!
