### ISSUE TITLE
Discussion: OAuth instead of PAT

### ISSUE THREAD

**Issue by cjdenio** [Matt-Gleich/fgh#2]
## Description

The login process could be simplified by implementing OAuth instead of requiring the user to generate a PAT.

Looking at [this line](https://git.io/JTaa0) in the GitHub CLI, it seems perfectly safe to embed OAuth credentials in a CLI.

**Comment by Matt-Gleich** [comment]
Oh, I forgot you could do this! Thanks, @cjdenio!

**Comment by cjdenio** [comment]
I'd be happy to write this (but no worries if you want to do it!)

**Comment by Matt-Gleich** [comment]
That would be great @cjdenio! Just invited you as a collaborator.

**Comment by cjdenio** [comment]
Awesome, thank you! I could have just forked it, but this works too :smile:

**Comment by Matt-Gleich** [comment]
Do you need me to make a new OAuth app?

**Comment by cjdenio** [comment]
Sure! You'll want to set the redirect URL to `http://localhost:9000/callback`
