### ISSUE TITLE
`fgh visualize` is rather slow

### ISSUE THREAD

**Issue by cjdenio** [Matt-Gleich/fgh#21]
`fgh visualize` often takes several minutes to run, leaving me in a constant state of baffled annoyance. I've tried benchmarking individual repos, and it seems like the issue may lie in the `LastUpdated` function. I'll do some more research tomorrow.

**Comment by cjdenio** [comment]
I'm on Linux, btw. I assume that it works fine for you on MacOS, so it's probably a Linux-specific issue.

**Comment by Matt-Gleich** [comment]
So `LastUpdated` checks every single file in the repo for its modification time. Does is take a really long time for big projects or for any project?

**Comment by cjdenio** [comment]
I've found that it varies between projects, but it generally takes a long time for every project. It's strange, because the only language I use with a massive package directory is Node, and fgh handles that :thinking:

**Comment by Matt-Gleich** [comment]
Do other commands like `fgh clean` take a really long time as well?

**Comment by cjdenio** [comment]
Yeah, `fgh clean` also takes way longer than it should. :intense-thonk:

**Comment by Matt-Gleich** [comment]
hmmm I'll spin up an Ubuntu VM and test it out later. Sorry about this!

**Comment by Matt-Gleich** [comment]
@cjdenio how long does it take to run and how many repos do you have?

**Comment by cjdenio** [comment]
I have 23 repositories, and it took 3 minutes and 45 seconds to run.

**Comment by Matt-Gleich** [comment]
@cjdenio so I wasn't able to reproduce this on my machine so I'll make a custom version later today with some time-based logs.

**Comment by cjdenio** [comment]
Thanks for trying! I'll do some more research; it could simply be the fact that my home dir isn't on an SSD (forgot to mention that 😬)

**Comment by Matt-Gleich** [comment]
Oh yeah, that might be it. I just added logs to the `time-logs` branch of this repo for the visualize cmd. Please try it out and send me the logs at your convenience :)

**Comment by Matt-Gleich** [comment]
@cjdenio any success with the time logs?

**Comment by Matt-Gleich** [comment]
Closing this out of the fact that this is most likely a hardware issue
