### ISSUE TITLE
Ignores Absolute path for structure_root

### ISSUE THREAD

**Issue by stratosgear** [Matt-Gleich/fgh#22]
## Description

Ignores absolute path in `structure_root`

## Steps to reproduce

Set:

`structure_root: "/mnt/repos"`

in your `~/.config/fgh/config.yaml`

Then:

`gfh clone  Matt-Gleich/fgh`

The project is checked out at `/home/username/mnt/repos`

I was expecting it to clone at:

`/mnt/data/`

**Comment by Matt-Gleich** [comment]
@stratosgear for backward compatibility I have a separate config option for this. Just add the following line to turn off the appending of the home dir to the front of the path:

```yaml
dont_append_home_dir: true
``` 

This is now in 2.5.1 of fgh!

**Comment by stratosgear** [comment]
Fine, but I think you are breaking a well established pattern here.  Absolute paths are absolute paths! :) (Cross platform absolute paths being a bitch, still)

It would make **no sense** to specify `structure_root: "/my/mount/point/my/repos"`  and simply because I didn't notice or didn't edit the `dont_append_home_dir` config to  have everything pile up on `/home/user/my/mount/point/my/repos`.

The `structure_root` config **even** has **root** in the name!  It simply doesn't make sense!

I believe you will have to improve on the docs on how `structure_root` works and drop the 'dont_append_home_dir'

**Comment by Matt-Gleich** [comment]
Agreed. I'll change this over and release a patch later today.

**Comment by Matt-Gleich** [comment]
@stratosgear this is now implemented in fgh v2.5.2. Just add `/` to the start of your path to make it absolute. Thanks for the input on this!
