### ISSUE TITLE
Make `remote not found` error output as a warning during `migrate`

### ISSUE THREAD

**Issue by szhu** [Matt-Gleich/fgh#24]
## Description

Most of my `fgh` commands that I run result in the following error:

```
░░░░░░░░░░░
░✗ ERROR ✗░
░░░░░░░░░░░

Failed to ask for the default remote

GOLANG ERROR (SHOW DEVELOPER):
please provide options to select from
```

## Steps to reproduce

Examples:

```
$ fgh migrate Code
⠋ Getting list of repos ░░░░░░░░░░░
░✗ ERROR ✗░
░░░░░░░░░░░

Failed to ask for the default remote

GOLANG ERROR (SHOW DEVELOPER):
please provide options to select from
```

```
$ fgh ls Matt-Gleich/fgh
░░░░░░░░░░░
░✗ ERROR ✗░
░░░░░░░░░░░

Failed to ask for the default remote

GOLANG ERROR (SHOW DEVELOPER):
please provide options to select from
```

**Comment by Matt-Gleich** [comment]
Hello @szhu! Sorry to hear that you are having this issue. I am going to be releasing a small patch later today for another issue and I will put some better error logs for this. I'll ping you here when it comes out.

**Comment by Matt-Gleich** [comment]
Hey @szhu! So I just added some logs for this in fgh v2.5.2. Once you've upgraded could you please give me the following resources?

1. Your fgh config file
2. The error message
3. The remotes for the repo that is causing this error
4. Your OS

**Comment by szhu** [comment]
Oh, thanks for updating that error message, I figured it out.

```
Failed to ask for the default remote in `/Users/Sean/Code/unpublished/xxxx`
```

Where `xxxx` is an unpushed Git repo that I manually created (no remotes). It would be nice if this wasn't fatal error.

**Comment by Matt-Gleich** [comment]
Great! I'll make sure that `migrate` old logs this error as a warning that it failed to move the repo. Just for some context, this is how I get the owner of the repo so it is pretty important for the whole migration process. Thank you for the feedback!

**Comment by szhu** [comment]
Thank you for the update and thank you so much for having such a fast and streamlined bug reporting process!

**Comment by Matt-Gleich** [comment]
A warning is now given for `fgh migrate` and `fgh update` in fgh v2.5.3. Thank you for the input on this!
