### ISSUE TITLE
Feature request: removing owner in `fgh ls`

### ISSUE THREAD

**Issue by cjdenio** [Matt-Gleich/fgh#25]
## Description

When getting a repo's path with `fgh ls`, you're required to pass in the owner's username if you don't own the repo (e.g. `Matt-Gleich/fgh`). It would be helpful if `fgh` could, after determining that the user _doesn't_ own the provided repo name, check for other cloned repos of the same name.

TL;DR: I wish `fgh ls blah` could find a locally cloned repo called `blah/blah`, even if my username isn't `blah`.

**Comment by Matt-Gleich** [comment]
Good idea!
