### ISSUE TITLE
fgh configure fails when folder is not yet created

### ISSUE THREAD

**Issue by jasonappah** [Matt-Gleich/fgh#28]
## Description
When I ran `fgh configure` for the first time, I received this error:
```
░░░░░░░░░░░
░✗ ERROR ✗░
░░░░░░░░░░░

Failed to write config secrets

GOLANG ERROR (SHOW DEVELOPER):
open /home/jasonantwiappah/.config/fgh/config.yaml: no such file or directory
```
## Steps to reproduce

I ran `fgh configure` after initially installing fgh.  I have a `~/.config` folder but no fgh folder within that. Once I manually created the folder and reran `fgh configure` everything worked. 

## Logs/Screenshots

![image](https://user-images.githubusercontent.com/30608521/103181681-7cf30780-4869-11eb-80b2-86195e66e2eb.png)

If you'd like I can make a PR to fix this, I've been meaning to learn go for a while ;)

**Comment by Matt-Gleich** [comment]
Hey @jasonappah! Sorry to hear that you are having this problem. Just pushed out a fix and should be released in fgh 2.5.5

**Comment by Matt-Gleich** [comment]
@jasonappah this is now out in fgh v2.5.5!

**Comment by jasonappah** [comment]
Thanks, everything seems to be working!
