### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by cjdenio** [Matt-Gleich/fgh#32]
## Description

I'd love to see native Apple Silicon (M1) support in fgh. This won't be realistic until Go 1.16 is released (probably sometime in February), but here are (untested) instructions for how you can build fgh for Apple Silicon:

**Requires a working [Go](https://golang.org) installation, as well as an M1 machine.**

1. Clone fgh with `git clone https://github.com/Matt-Gleich/fgh`
2. `go get golang.org/dl/go1.16beta1` to install the latest Go 1.16 beta **(will be safely installed alongside your current installation)**
3. Run `go1.16beta1 build .` in the `fgh` directory
4. Observe the `fgh` binary that has been compiled into existence!

**Comment by Matt-Gleich** [comment]
Thanks for the info @cjdenio! We also need to wait for homebrew to support and goreleaser support.
