### ISSUE TITLE
Path subcommand

### ISSUE THREAD

**Issue by cjdenio** [Matt-Gleich/fgh#8]
## Description

A command like `fgh path repo_name` could be used in conjunction with `cd` like so:
```
cd `fgh p Matt-Gleich/fgh`
```

**Comment by Matt-Gleich** [comment]
Good idea!

**Comment by cjdenio** [comment]
Ooh, then people could set up a bash alias to make `ghcd repo` work

**Comment by Matt-Gleich** [comment]
We could have it so the root command just does cd

**Comment by Matt-Gleich** [comment]
I have to figure out how to do parent process path exchanges tho

**Comment by cjdenio** [comment]
Sub-processes can't run `cd` at the shell level, though :cry:

**Comment by Matt-Gleich** [comment]
How does ranger do it?

**Comment by cjdenio** [comment]
Good question :thinking:

**Comment by Matt-Gleich** [comment]
We need the thonk emoji in GitHub issues

**Comment by cjdenio** [comment]
YES GITHUB NEEDS CUSTOM EMOJIS lol

**Comment by Matt-Gleich** [comment]
lol
